# Generated by Django 5.0 on 2023-12-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
