# Generated by Django 5.0 on 2023-12-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_card_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='owner',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='starting_balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='base.card')),
            ],
        ),
    ]
