# Generated by Django 5.0 on 2024-01-20 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_card_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='gc_total_bal',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
