# Generated by Django 5.0 on 2023-12-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_amount_card_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='starting_balance',
        ),
    ]
