# Generated by Django 5.0 on 2023-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_card_starting_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='original_balance',
            field=models.FloatField(default=0),
        ),
    ]
