# Generated by Django 5.0 on 2024-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_card_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bus_img',
            field=models.ImageField(default='storefront.svg', null=True, upload_to=''),
        ),
    ]
